# Generated by Django 5.0.6 on 2024-07-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ters_gallery', '0002_collection_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='is_main',
            field=models.BooleanField(default=False, help_text='Выбор коллекции для отображения на главной странице.'),
        ),
    ]
