# Generated by Django 5.0.7 on 2024-07-18 17:53

import django.db.models.deletion
import ters_gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ters_gallery', '0003_alter_product_name_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(default=ters_gallery.models.Collection.get_default_pk, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='ters_gallery.collection'),
        ),
    ]
