# Generated by Django 5.0.7 on 2024-07-18 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ters_gallery', '0004_alter_product_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='collections/')),
            ],
        ),
        migrations.AlterField(
            model_name='collection',
            name='main_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_for_collections', to='ters_gallery.collectionimage'),
        ),
    ]
