# Generated by Django 5.0.6 on 2024-07-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="is_main",
            field=models.BooleanField(default=False),
        ),
    ]
