# Generated by Django 5.2 on 2025-04-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_collection_is_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_image', models.ImageField(upload_to='about_page/')),
                ('bottom_image', models.ImageField(upload_to='about_page/')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='image',
            field=models.ImageField(default='materials/LEATHER.JPG', upload_to='materials/'),
        ),
    ]
