# Generated by Django 5.2 on 2025-04-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_aboutpagesettings_material_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpagesettings',
            options={'verbose_name': "Настройки страницы 'О нас'", 'verbose_name_plural': "Настройки страницы 'О нас'"},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': 'Коллекция', 'verbose_name_plural': 'Коллекции'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основная картинка'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='is_main',
            field=models.BooleanField(default=False, help_text='Выбор коллекции для отображения на главной странице. При выборе, заменяет выбранную до этого момента.', verbose_name='Отображать на главной странице'),
        ),
    ]
