# Generated by Django 5.2 on 2025-09-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_aboutpagesettings_ideology_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detailed_materials',
            field=models.TextField(blank=True, help_text='Подробное описание материалов'),
        ),
    ]
