migrate:
	python manage.py makemigrations && python manage.py migrate

run:
	python manage.py runserver

load:
	python manage.py loaddata fixtures.json

dump:
	python manage.py dumpdata > fixtures.json