name: Deploy to Production

# Запускаем после успешного CI
on:
  workflow_run:
    workflows: ['Build & Push Docker Images']
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy production compose to server
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_SSH_PASSWORD }}
          source: 'docker-compose.prod.yml'
          target: '/home/deploy/ters/docker-compose.yml'

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_SSH_PASSWORD }}

          script: |
            # Заходим в папку с compose-файлом
            cd /home/deploy/ters

            # Перетягиваем свежие теги
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ters-backend:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ters-frontend:latest

            # Перезапускаем контейнеры через compose
            docker compose down
            docker compose up -d --remove-orphans
